(in-package :cl-java-sound-client)

(defclass connection ()
  ((port :initarg :port :initform 9000)
   (host :initarg :host :initform "localhost")
   (controller :initform nil)
   (socket :initform nil)
   (stream :initform nil)
   (send-message-lock :initform (bt:make-lock))
   (requested-frame-count :initform 0)
   (write-frames-chunk-length :initform 10000)
   (write-frames-sample-buffer :initform nil)))

(defgeneric start-message-loop (connection))
(defgeneric handle-message (connection message))
(defgeneric send-start-message (connection))
(defgeneric send-stop-message (connection))
(defgeneric send-frames-message (connection))
(defgeneric send-init-message (connection &key sample-rate channel-count buffer-size))
(defgeneric close-connection (connection))
(defgeneric send-init-session-data (connection))
(defgeneric set-controller (connection controller))
(defun get-controller (connection)
  (slot-value connection 'controller))
(defun write-frames-chunk-length (connection)
  (slot-value connection 'write-frames-chunk-length))
(defun write-frames-sample-buffer (connection)
  (slot-value connection 'write-frames-sample-buffer))


